#12 加入薪資所得稅計算
jodeci/fortuna pull request #15
Opened 2019-02-27 08:14 UTC by MindyTai

2019-02-27 08:29 UTC, jodeci commented on app/models/payroll_detail.rb
> +  scope :owner_income, ->(year:, month:) { where(year: year, month: month, owner: true) }
請問這個用意是？（負責人只會有一個人）

2019-02-27 08:30 UTC, jodeci commented on Gemfile.lock
> +   1.16.6
你應該用同一個版本的 bundler 去 bundle, 保持 Gemfile.lock 不變動

2019-02-27 08:31 UTC, jodeci commented on .travis.yml
> +  - bundle exec rake test
多了奇怪的東西 XD

2019-02-27 08:32 UTC, jodeci commented on app/services/calculatable.rb
> +  def insurance_tax
命名用 insured_salary_tax 比較好

2019-02-27 08:33 UTC, jodeci commented on app/services/health_insurance_service/company_coverage.rb
> +      row.sum(:amount) - row.sum(:subsidy_income)
同上，owner 只應該有一個，這裡不該被修改？

2019-02-27 08:34 UTC, jodeci commented on app/services/income_tax_service/insurance_salary.rb
> +  class InsuranceSalary
命名應該用 InsurancedSalary

2019-03-03 06:05 UTC, jodeci commented on app/services/income_tax_service/insuranced_salary.rb
> +      insuranced_salary_tax
這裡有幾個點可以思考：

1. 我們把「一般薪資所得的所得稅計算」抽成一個物件，目的是要讓它負責「所有和一般薪資所得的所得稅有關」的計算，讓其他物件只需要呼叫 InsurancedSalary.call 就可以得到值，不需要知道裡面是怎麼算的。

2. 對 InsurancedSalary 自己來說，它（最終）要做的事情應該是：
    - 判斷公司是採用哪一種計算方式（A: 統一扣 5% 或 B: 人工查表）
    - 如果是 A 方案，就要去做 5% 的計算
    - 如果是 B 方案，就要去讀 salary.income_tax 的值（這欄也建議可以改叫 salary.fixed_income_tax 不然也滿容易混淆的）
        - 要做得更完整的話，應該先判斷該 employee 的薪資若低於免稅額就直接回傳 0
    - 回傳 A 或 B 的值

雖然現階段只有實做 B 方案，但整個思路是一樣的，因此：

```
  def insuranced_salary_tax
    payroll.salary.income_tax
  end
```

這應該是 InsurancedSalary 內部的方法，不該抽去 Calculatable（並且一般來說，code 被重覆用在三個以上的地方才會抽出來）

2019-03-03 06:05 UTC, jodeci commented on app/services/income_tax_service/insuranced_salary.rb
> +    attr_reader :payroll, :call_type
:call_type 沒有用到要記得移掉

2019-03-03 06:13 UTC, jodeci commented on app/services/income_tax_service/insuranced_and_irregular_income.rb
> +  class InsurancedAndIrregularIncome
不要這樣命名 😂 
命名時要去想，這個物件的工作是什麼？
它的工作是計算「有勞保的正職員工，可能被徵收的所得稅」
萬一之後多了第三種要收的稅，總不能改成 InsurancedAndIrregularIncomeAndWhateverIncome 吧 XD

用像是 IncomeTaxService::RegularEmployee 之類的命名會好很多

2019-03-03 06:14 UTC, jodeci commented on app/services/income_tax_service/insuranced_and_irregular_income.rb
> +    include Calculatable
沒有用到的 module 就不需要 include

2019-03-04 03:23 UTC, jodeci commented on app/services/income_tax_service/insuranced_salary.rb
> +    def insuranced_salary_tax
這個方法應該做成 private

「一個物件盡量只做一件事情」==> 「盡量只提供一個 public 方法」

2019-03-04 04:16 UTC, jodeci commented on app/services/income_tax_service/regular_income.rb
> +  class RegularIncome
「RegularIncome」的話，只有「一般所得」的意義
（字面上，在 RegularIncome 的計算中包括 IrregularIncome 不合理吧 XD）

這個物件是要處理「正職員工的所得稅」，這包括了一般薪資所得和獎金所得，
因此命名用「RegularEmployee」或「InsurancedEmployee」會更貼切

2019-03-04 04:48 UTC, jodeci commented on test/services/income_tax_service/insuranced_salary_test.rb
> +        salary: build(:salary, monthly_wage: 30000, income_tax: income_tax),
這樣不會噴錯嗎？欄位應該改名了？

2019-03-04 04:58 UTC, MindyTai commented on test/services/income_tax_service/insuranced_salary_test.rb
> +        salary: build(:salary, monthly_wage: 30000, income_tax: income_tax),
他竟然不會噴錯 😂
我再仔細檢查一番

2019-03-04 10:38 UTC, jodeci requested changes

2019-03-04 10:38 UTC, jodeci commented on test/services/income_tax_service/regular_employee_test.rb
> +  class RegularEmployeeTest < ActiveSupport::TestCase
因為 InsurancedSalaryTest 和 IrregularIncomeTest 已經涵蓋到真正的功能測試，這邊不需要重覆測。

RegularEmployeeTest 要測的應該是「是否有呼叫到 InsurancedSalary 和 IrregularIncome？」（回傳的結果不重要，重要的是有呼叫到）

mock 的寫法可以參考 dispatcher

2019-03-05 03:32 UTC, jodeci approved these changes

2019-03-05 03:32 UTC, merged