約聘人員薪資扣除所得稅
jodeci/fortuna pull request #16
Opened 2019-03-06 03:06 UTC by MindyTai

2019-03-06 05:03 UTC, jodeci requested changes

2019-03-06 05:03 UTC, jodeci commented on lib/tasks/sample.csv
> +李小華,2019-03-01,2019-03-31,A987654321,1999-04-04,,,,salary,,2018-01-01,contractor,50000,0,50,0,0,0,0,0,0,0,business
雖然無傷大雅，但請問為什麼會改到這裡？
PR 要盡量保持單純，不要放進「和修改目的無關」的東西

2019-03-06 05:03 UTC, jodeci commented on test/services/statement_service/splitter_test.rb
> +      subject = prepare_subject(tax_code: 50, insured_for_health: 800, insured_for_labor: 45800, wage: 40000, fixed_income_tax: 1000)
SplitterTest 測試的是「有沒有正確被拆單」，拆單的功能並沒有改變，其實不需要改測試
你真正需要做的應該是寫「paid_amount 的值是否正確」的測試才對

2019-03-06 05:03 UTC, jodeci commented on app/services/statement_service/splitter.rb
> +      salary.parttime_income_uninsured_for_health? ? income_before_withholdings - IncomeTaxService::InsurancedSalary.call(payroll) : income_before_withholdings
1. 把 paid_amount 移進 calculatable.rb
2. 試著 refactor paid_amount / income_before_withholdings / taxable_income, 整成只有 paid_amount 和 taxable_income
3. 補 paid_amount 的測試

2019-03-06 06:06 UTC, MindyTai commented on lib/tasks/sample.csv
> +李小華,2019-03-01,2019-03-31,A987654321,1999-04-04,,,,salary,,2018-01-01,contractor,50000,0,50,0,0,0,0,0,0,0,business
因為我之前測資 end_date 設到 2019-02-28
若沒改到測資會顯示在  ```離職員工```
為讓為讓測資統一顯示在 ```新增員工```
所以更改測資

會注意 PR 只放進「和修改有關」的檔案

2019-03-06 06:07 UTC, jodeci commented on lib/tasks/sample.csv
> +李小華,2019-03-01,2019-03-31,A987654321,1999-04-04,,,,salary,,2018-01-01,contractor,50000,0,50,0,0,0,0,0,0,0,business
這狀況你應該直接改本機端資料就好了 XD

2019-03-06 06:12 UTC, MindyTai commented on lib/tasks/sample.csv
> +李小華,2019-03-01,2019-03-31,A987654321,1999-04-04,,,,salary,,2018-01-01,contractor,50000,0,50,0,0,0,0,0,0,0,business
也是 XD
知道了 ！

2019-03-11 05:56 UTC, jodeci commented on test/services/calculatable_test.rb
> +  def test_paid_amount
這邊可以拆成三個 test

2019-03-11 05:56 UTC, jodeci commented on app/services/calculatable.rb
> +  def income_after_withholdings
邏輯沒有問題，但這樣命名很怪 :joy:
概念上應該是 income_before_withholdings_after_tax 才對？

2019-03-11 05:56 UTC, jodeci commented on app/services/calculatable.rb
> +  def regular_paid_amount
1. 改名的原因是？
2. 為什麼是用 salary.role 做判斷？

2019-03-11 08:13 UTC, MindyTai commented on app/services/calculatable.rb
> +  def regular_paid_amount
1. 原本是因為其他檔有相同的 paid_amount 的變數，會容易混淆，所以想說換掉變數名稱，但剛剛想到之前有說要把其他檔的 paid_amount 拿掉，所以會改回來。

2. 因為想說只是要判斷 contractor 這個條件， 所以覺得用 `payroll.salary.role == "contractor" ` 會讓條件比較明確，也更具可讀性。

2019-03-11 08:20 UTC, jodeci commented on app/services/calculatable.rb
> +  def regular_paid_amount
不是這個問題，問題是 salary.role 和所得稅的計算無關啊

2019-03-12 11:13 UTC, jodeci requested changes

2019-03-12 11:13 UTC, jodeci commented on app/decorators/statement_decorator.rb
> -  def paid_amount
為什麼會改到這裡 :joy:
這是 StatementDecorator 的方法，和這次修改完全無關，雖然同名但也不在同一個 namepsace 下照理不會有任何影響？

2019-03-12 11:13 UTC, jodeci commented on test/services/calculatable_test.rb
> +    subject_for_regular_employees = DummyObject.new(
拆開成兩個方法就是變數名稱也可以更簡短的意思，用 subject 就可以了（以下同）
以及可以測完整一點，確保所有情況都有測到：

1. tax_code: 50, insured_for_labor > 0, insured_for_health > 0
2. tax_code: 50, insured_for_labor > 0, insured_for_health: 0
3. tax_code: 50, insured_for_labor: 0, insured_for_health: 0
4. tax_code: 9A, insured_for_labor: 0, insured_for_health: 0

這樣 build subject 這段就可以獨立抽出來，再去 stub income_before_withholdings 和 income_tax 的值，就知道有沒有算錯了

2019-03-12 11:13 UTC, jodeci commented on app/services/calculatable.rb
> +    paid_amount + labor_insurance + health_insurance - subsidy_income
taxable_income 用 paid_amount 計算有個盲點是，paid_amount 有可能會算進稅金，但 taxable_income 是用來計算稅的，邏輯上應該要排除掉

（例如收入 30000 元，扣 5% 稅金 = 1500 元，taxable income 應為 30000 而非 28500）

1. 所以你這邊應該用新版的 income_before_withholdings 才對
2. 可以想一下是否要調整 income_before_withholdings 和 basic_deduction 的邏輯，避免勞健保的重覆加減

2019-03-12 11:13 UTC, jodeci commented on app/services/calculatable.rb
> +    income_before_withholdings - income_tax_for_parttime_income_uninsured_for_health
應該直接呼叫現成的 income_tax 就可以了？

2019-03-12 11:13 UTC, jodeci commented on app/services/calculatable.rb
> +  def income_tax_for_parttime_income_uninsured_for_health
這個是多餘的

2019-03-12 11:13 UTC, jodeci commented on app/services/calculatable.rb
> +    if payroll.salary.parttime_income_uninsured_for_health?
我對是否該這樣判斷還有疑慮，先維持這樣，把下面的測試補齊再看看要不要調整

2019-03-15 06:50 UTC, jodeci commented on app/services/calculatable.rb
> +    if payroll.salary.parttime_income_uninsured_for_health? and payroll.salary.insured_for_labor.positive?
為什麼不把這個條件抽出來，在 salary 多加一個方法就好 :joy:

2019-03-15 07:10 UTC, jodeci commented on test/services/calculatable_test.rb
> +  def test_taxable_income_for_parttime_income_uninsured_for_labor
1. 這個算出來應該要是 80 才對
2. 敘述說是 uninsured_for_labor 的話, labor_insurance 應該是 0 才對

2019-03-15 07:11 UTC, jodeci commented on test/services/calculatable_test.rb
> +  def test_taxable_income_for_parttime_income_uninsured_for_health
這個算出來也應該是 80 才對

2019-03-15 07:11 UTC, jodeci commented on test/services/calculatable_test.rb
> +  def test_taxable_income_for_professional_services
這個算出來也是 80 才對

2019-03-15 07:33 UTC, jodeci requested changes

2019-03-15 07:33 UTC, jodeci commented on app/services/calculatable.rb
> +  def taxable_income_before_tax
我覺得你還是沒有弄懂 taxable income 的意義，這個命名一點都不合理啊 :joy:
再列一次（這裡用 5% 的扣法方便說明）：

王小明 ：
月薪 36,000 元
勞保自負 799 元
健保自負 511 元
加班費（免稅） 3000 元 <-- subsidy_income
年終獎金（應稅）100,000 元 <-- bonus_income

薪資所得稅 = 36000 * 5% = 1800  <-- taxable income 是 36000, 是計算的標準
獎金所得稅 = 100000 * 5% = 5000

公司實際支付給他的是 130,890  --> paid amount

把這段想清楚再把測試修掉看看吧

2019-03-15 15:05 UTC, elct9620 commented
想超久才懂 `80` 的原因，不過這樣計算會有問題是在 `labor_insurance` 和 `health_insurance` 有誤算的時候會得到錯誤的結果吧 🤔 

雖然數值是寫死在 DB 裡面的 XD

2019-03-19 07:38 UTC, jodeci commented on app/services/calculatable.rb
> +    payroll.salary.monthly_wage + payroll.salary.equipment_subsidy + payroll.salary.supervisor_allowance + extra_income - deduction - extra_income_of_bonus_and_subsidy
為什麼不是直接用 total_income 去減掉就好？這樣時薪制的會算不到吧，而且不是又重覆加減了嗎？

    + extra_income - extra_income_of_bonus_and_subsidy

2019-03-19 07:41 UTC, jodeci commented on app/services/calculatable.rb
> +  def extra_income_of_bonus_and_subsidy
我認這個方法應該是多餘的，真有需要的話也有現成的 bonus_income + subsidy_income 可以用

2019-03-19 07:49 UTC, jodeci commented on test/services/calculatable_test.rb
> +  def test_taxable_income
這個的結果應該是 102 才對 :joy:
每月固定發的「補助」，不適用免稅的規定，
免稅的只有 subsidy_income 這一塊

2019-03-19 07:55 UTC, jodeci commented on test/services/calculatable_test.rb
> +    subject = DummyObject.new(
頭尾的 subject 像是多的？

2019-03-19 08:17 UTC, jodeci commented on app/services/calculatable.rb
> +  def deduction
你又在重覆加減了 :joy: 你試著用這個當基礎去重新組合你的算式：

    def withholdings
        labor_insurance + health_insurance
    end

    def basic_deductions
        leavetime + sicktime + payroll.extra_deductions
    end

2019-03-26 05:49 UTC, merged